// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLog(arg1:string,arg2:main.LogType):Promise<void>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function SendMail(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:string):Promise<string>;

export function SubscribeToLogs(arg1:any):Promise<void>;
