// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2) {
  return window['go']['main']['App']['AddLog'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function SendMail(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMail'](arg1, arg2, arg3, arg4, arg5);
}
